[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  # The openAIKey environment variable set in Netlify UI will be available to webpack

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8080

# Headers for better security and CORS handling - Allow embedding in Missive
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Remove X-Frame-Options to allow iframe embedding
    # Add CSP to allow framing from Missive domains
    Content-Security-Policy = "frame-ancestors 'self' https://*.missiveapp.com https://mail.missiveapp.com;"
    
# Enable gzip compression
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 